# Config dict to be used for pomdp simulation and inference through sampling
# All tags are mandatory!
# The ones with default value given as comment, can be left empty to use default value.
# All others must be specified!

graph_struct:
  $X_{1}$: []
  $X_{2}$: []

Q_dict:  # default gamma-distributed

Q_gamma_params: # default alpha:2, beta:2
  $X_{1}$:
    alpha: [5,10]
    beta: [5,20]
  $X_{2}$:
    alpha: [20,20]
    beta: [20,10]

states: [0, 1]  # default [0, 1]
initial_prob:  # default equiprobable

$Q_{3}$: {'0': [[-0.5, 0.5],
                [7, -7]],
          '1': [[-16, 16],
                [0.02, -0.02]]}

observation_space: [0, 1, 2]
action_space: [0, 1]
obs_model:
  [[1., 0., 0.],
   [0., 1., 0.],
   [0., 1., 0.],
   [0., 0., 1.]]
#  [[0.98, 0.01, 0.01],
#   [0.01, 0.98, 0.01],
#   [0.01, 0.98, 0.01],
#   [0.01, 0.01, 0.98]]
#  [[0.95, 0.025, 0.025],
#   [0.025, 0.95, 0.025],
#   [0.025, 0.95, 0.025],
#   [0.025, 0.025, 0.95]]
#  [[0.9, 0.05, 0.05],
#   [0.05, 0.9, 0.05],
#   [0.05, 0.9, 0.05],
#   [0.05, 0.05, 0.9]]
#  [[0.85, 0.075, 0.075],
#   [0.075, 0.85, 0.075],
#   [0.075, 0.85, 0.075],
#   [0.075, 0.075, 0.85]]
#  [[0.8, 0.1, 0.1],
#   [0.1, 0.8, 0.1],
#   [0.1, 0.8, 0.1],
#   [0.1, 0.1, 0.8]]
#  [[0.7, 0.15, 0.15],
#   [0.15, 0.7, 0.15],
#   [0.15, 0.7, 0.15],
#   [0.15, 0.15, 0.7]]

# 'particle filter', 'exact update', 'van_particleFilter' in a listDENEW
belief_update_method: [ 'exact update', 'van_particleFilter', 'particle filter']

n_particle: 200
time_increment: 0.01

policy_type: detFunction  # deterministic_df, stochastic_df or detFunction (deterministic function)

marginalize: True

t_max: 5 # default  20
n_train: 1
n_test: 0

n_obs_model: 3

seed: 0
import_data: False
import_psi: True

misc_tag: ''
