# Config dict to be used for pomdp simulation and inference through sampling
# All tags are mandatory!
# The ones with default value given as comment, can be left empty to use default value.
# All others must be specified!

graph_struct:
  $X_{1}$: []
  $X_{2}$: []

Q_dict:  # default gamma-distributed

Q_gamma_params: # default alpha:2, beta:2
  $X_{1}$:
    alpha: [5,2]
    beta: [2,1]
  $X_{2}$:
    alpha: [1,4]
    beta: [2,0.5]

parent_list:  # default  ['X1', 'X2']
states: [0, 1]  # default [0, 1]
initial_prob:  # default equiprobable

$Q_{3}$: {'0': [[-0.5, 0.5],
                [25, -25]],
          '1': [[-32, 32],
                [0.02, -0.02]]}

observation_space: [0, 1, 2]
action_space: [0, 1]
obs_model: [[1., 0., 0.],
            [0., 1., 0.],
            [0., 1., 0.],
            [0., 0., 1.]]

belief_update: particle_filter  # particle_filter or exact
n_particle: 200

policy: deterministic  # deterministic, stochastic or function

marginalize: True

time_grain: 0.01
t_max: 3 # default  20
n_train: 2
n_test: 1

n_obs_model: 2

seed: 3
import_data: 1589321877_3sec_2train_1test_2model_deterministicPolicy_particle_filter200_seed3
import_psi: False
