# Config dict to be used for pomdp simulation and inference through sampling
# All tags are mandatory!
# The ones with default value given as comment, can be left empty to use default value.
# All others must be specified!

graph_struct:
  X: []
  Y: []

parent_list:  # default  ['X', 'Y']
states: [0, 1]  # default [0, 1]
initial_prob:  # default equiprobable
Q_dict:  # default randomly generated
observation_space: [0, 1, 2]

action_space: [0, 1]
obs_model: [[0, 1, 0],
            [0, 1, 0],
            [1, 0, 0],
            [0, 1, 0]]
policy: function  # deterministic, stochastic or function

time_grain: 0.01
t_max: 3 # default  20
n_traj: 10
n_obs_model: 5

seed: 1
