# Config dict to be used for pomdp simulation and inference through sampling
# All tags are mandatory!
# The ones with default value given as comment, can be left empty to use default value.
# All others must be specified!

graph_struct:
  $X_{1}$: []
  $X_{2}$: []

Q_dict:  # default gamma-distributed

Q_gamma_params: # default alpha:2, beta:2
  $X_{1}$:
    alpha: [5,10]
    beta: [5,20]
  $X_{2}$:
    alpha: [20,20]
    beta: [20,10]

states: [0, 1]  # default [0, 1]
initial_prob:  # default equiprobable

$Q_{3}$: {'0': [[-0.5, 0.5],
                [2, -2]],
          '1': [[-3, 3],
                [0.02, -0.02]]}

observation_space: [0, 1, 2]
action_space: [0, 1]
obs_model:

# "particleFilter", "exactUpdate", "particleFilter_van" in a list
belief_update_method: ["particleFilter"]
n_particle: 200

policy_type: detFunction  # deterministic_df, stochastic_df or detFunction (deterministic function)

marginalize: True

time_increment: 0.01
t_max: 5 # default  20
n_train: 200
n_test: 0

n_obs_model: 3

seed: 0
import_data: False
import_psi: True

misc_tag: ''
